spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortener?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ProfileServiceConnectionPool
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 60000
      connection-timeout: 30000
      idle-timeout: 600000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false
