spring:
  application:
    name: urlshortener-profile-service
  kafka:
    bootstrap-servers: localhost:9092
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8566

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
