spring:
  application:
    name: urlshortener-profile-service
  kafka:
    bootstrap-servers: localhost:9092
  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8566

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /admin/management
  endpoint:
    health:
      show-details: always
    info:
      access: read_only
    metrics:
      access: read_only

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
