spring:
  application:
    name: urlshortener-profile-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

kafka:
  notification:
    topic:
      name: urlshortener.notifications.email
      partitions: 1
      replication-factor: 1
